name: Go Matrix
on: [push, pull_request]

jobs:

  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ "1.23" ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: ['x64']
        # Makefileにしたくね？
        main: 
          - examples/macros/get
          - examples/macros/patch
          - examples/scenes/get
          - examples/scenes/patch
          - examples/tester

    steps:
      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}(${{ matrix.arch }})
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          architecture: ${{ matrix.arch }}

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/cache
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.go-version }}-go-

      - name: Lint
        run: golangci-lint run

      - name: Test
        run: go test -v -cover ./...
      
      - name: Build
        env:
          GO_CMD_MAIN: ${{ matrix.main }}
        run: goreleaser build --auto-snapshot --clean
